/**
 * Core Type Definitions for the Code Generation Engine
 * 
 * All JSDoc types used throughout the engine for maximum IDE support.
 */

/**
 * @typedef {'string' | 'number' | 'boolean' | 'date' | 'enum' | 'object' | 'array'} FieldType
 */

/**
 * @typedef {'table' | 'relation'} DataSourceType
 */

/**
 * @typedef {'text' | 'email' | 'password' | 'number' | 'phone' | 'url' | 'date' | 'richtext' | 'select' | 'multiselect' | 'toggle' | 'tags'} InputType
 */

/**
 * @typedef {'required' | 'email' | 'minLength' | 'maxLength' | 'min' | 'max' | 'pattern' | 'custom'} ValidationRuleType
 */

/**
 * @typedef {'none' | 'relation' | 'computed' | 'enum' | 'date' | 'boolean' | 'auto'} FieldCategory
 */

/**
 * @typedef {Object} Field
 * @property {string} name - Field name (camelCase)
 * @property {string} displayName - Human-readable display name
 * @property {FieldType} type - Data type
 * @property {FieldCategory} category - Semantic category for UI generation
 * @property {boolean} required - Whether field is required
 * @property {boolean} unique - Whether field has unique constraint
 * @property {boolean} isPrimaryKey - Whether field is the primary key
 * @property {boolean} isAutoGenerated - Whether field is auto-generated (ID, createdAt, etc.)
 * @property {string} [relationTarget] - Target entity for relation fields
 * @property {string} [relationType] - Type of relation (one-to-many, many-to-many, etc.)
 * @property {string} [relationName] - Name of the relation
 * @property {Array<{rule: string, value?: *}>} [validations] - Validation rules
 * @property {*} [defaultValue] - Default value
 * @property {string} [example] - Example value for documentation
 * @property {string} [description] - Field description
 * @property {Array<{value: string, label: string}>} [options] - Options for enum/select fields
 * @property {InputType} [inputType] - UI input type hint
 * @property {boolean} [isArray] - Whether field stores an array
 * @property {boolean} [isOptional] - Whether field is optional
 * @property {boolean} [isRelation] - Whether field is a relation
 * @property {boolean} [isComputed] - Whether field is computed/virtual
 * @property {boolean} [isEnum] - Whether field is an enum
 * @property {boolean} [isDate] - Whether field is a date
 * @property {boolean} [isBoolean] - Whether field is a boolean
 * @property {boolean} [isNumber] - Whether field is a number
 * @property {boolean} [isString] - Whether field is a string
 * @property {boolean} [isObject] - Whether field is an object
 */

/**
 * @typedef {Object} Relation
 * @property {string} name - Relation name
 * @property {string} type - Relation type (one-to-one, one-to-many, many-to-many)
 * @property {string} from - Source entity name
 * @property {string} to - Target entity name
 * @property {string} fromField - Source field name
 * @property {string} [toField] - Target field name
 * @property {boolean} [isArray] - Whether relation is an array
 * @property {boolean} [isRequired] - Whether relation is required
 * @property {boolean} [isOptional] - Whether relation is optional
 * @property {boolean} [isSelfRelation] - Whether relation is a self-relation
 */

/**
 * @typedef {Object} Entity
 * @property {string} name - Entity name (PascalCase)
 * @property {string} displayName - Human-readable display name
 * @property {string} description - Entity description
 * @property {string} tableName - Database table name
 * @property {Array<Field>} fields - Entity fields
 * @property {Array<Relation>} relations - Entity relations
 * @property {Object} metadata - Additional metadata
 * @property {string} [icon] - Icon name for UI
 * @property {string} [color] - Primary color
 * @property {boolean} [isEditable] - Whether entity is editable
 * @property {boolean} [isDeletable] - Whether entity is deletable
 * @property {boolean} [isExportable] - Whether entity is exportable
 * @property {boolean} [isImportable] - Whether entity is importable
 * @property {boolean} [isAuth] - Whether entity is used for authentication
 * @property {boolean} [isRBAC] - Whether entity is used for role-based access control
 * @property {boolean} [isAudit] - Whether entity is used for audit logging
 * @property {boolean} [isSoftDelete] - Whether entity uses soft delete
 * @property {boolean} [isSearchable] - Whether entity is searchable
 * @property {boolean} [isFilterable] - Whether entity is filterable
 * @property {boolean} [isSortable] - Whether entity is sortable
 * @property {boolean} [isPaginatable] - Whether entity is paginatable
 * @property {boolean} [isExportableToCSV] - Whether entity can be exported to CSV
 * @property {boolean} [isExportableToPDF] - Whether entity can be exported to PDF
 * @property {boolean} [isExportableToExcel] - Whether entity can be exported to Excel
 * @property {boolean} [isExportableToJSON] - Whether entity can be exported to JSON
 * @property {boolean} [isExportableToXML] - Whether entity can be exported to XML
 */

/**
 * @typedef {Object} Config
 * @property {string} name - Project name
 * @property {string} description - Project description
 * @property {string} version - Project version
 * @property {string} author - Author name
 * @property {string} license - License type
 * @property {string} repository - Repository URL
 * @property {string} homepage - Homepage URL
 * @property {string} database - Database type (postgresql, mysql, sqlite)
 * @property {string} orm - ORM type (prisma, drizzle, typeorm, sequelize, mongoose)
 * @property {string} apiStyle - API style (rest, graphql, trpc)
 * @property {string} authProvider - Authentication provider
 * @property {string} storageProvider - Storage provider
 * @property {string} cacheProvider - Cache provider
 * @property {string} queueProvider - Queue provider
 * @property {string} emailProvider - Email provider
 * @property {string} paymentProvider - Payment provider
 * @property {string} analyticsProvider - Analytics provider
 * @property {string} monitoringProvider - Monitoring provider
 * @property {string} searchProvider - Search provider
 * @property {string} cdnProvider - CDN provider
 * @property {string} loggingProvider - Logging provider
 * @property {string} testProvider - Test provider
 * @property {string} buildTool - Build tool (webpack, vite, rollup, esbuild)
 * @property {string} packageManager - Package manager (npm, yarn, pnpm)
 * @property {string} linter - Linter (eslint, biome)
 * @property {string} formatter - Formatter (prettier, biome)
 * @property {string} testFramework - Test framework (jest, vitest, mocha)
 * @property {string} cssFramework - CSS framework (tailwind, styled-components, emotion)
 * @property {string} uiLibrary - UI library (radix, shadcn, headlessui, chakra, antd, mui)
 * @property {string} stateManagement - State management (zustand, jotai, redux, mobx, context)
 * @property {string} dataFetching - Data fetching (tanstack-query, swr, axios, fetch)
 * @property {string} formLibrary - Form library (react-hook-form, formik, final-form)
 * @property {string} validationLibrary - Validation library (zod, yup, joi, ajv)
 * @property {string}国际化 - Internationalization library (i18next, react-intl, formatjs)
 * @property {Object} [options] - Additional options
 */

/**
 * @typedef {Object} GeneratedFile
 * @property {string} path - File path
 * @property {string} content - File content
 * @property {'create' | 'update' | 'delete'} action - File action
 * @property {Object} [metadata] - Additional metadata
 */

/**
 * @typedef {Object} GeneratorOptions
 * @property {string} outputPath - Output directory path
 * @property {boolean} overwrite - Whether to overwrite existing files
 * @property {boolean} dryRun - Whether to perform a dry run
 * @property {boolean} verbose - Whether to enable verbose logging
 * @property {string[]} [entities] - Specific entities to generate
 * @property {string[]} [components] - Specific components to generate
 * @property {string[]} [features] - Specific features to generate
 * @property {Object} [config] - Custom configuration
 */

/**
 * @typedef {Object} GeneratorResult
 * @property {GeneratedFile[]} files - Generated files
 * @property {string[]} warnings - Warning messages
 * @property {string[]} errors - Error messages
 * @property {Object} stats - Generation statistics
 * @property {number} stats.files - Number of files generated
 * @property {number} stats.lines - Number of lines generated
 * @property {number} stats.duration - Generation duration in milliseconds
 */

/**
 * @typedef {Object} ValidationSchema
 * @property {string} name - Schema name
 * @property {Object} fields - Field validations
 * @property {Object} [messages] - Custom error messages
 */

/**
 * @typedef {Object} APIEndpoint
 * @property {string} path - Endpoint path
 * @property {string} method - HTTP method
 * @property {string} name - Endpoint name
 * @property {string} description - Endpoint description
 * @property {Array<{name: string, type: string, required: boolean, description?: string}>} [params] - Path parameters
 * @property {Object} [query] - Query parameters
 * @property {Object} [body] - Request body schema
 * @property {Object} [response] - Response schema
 * @property {Object} [errors] - Error responses
 * @property {string[]} [tags] - Endpoint tags
 * @property {boolean} [auth] - Whether authentication is required
 * @property {boolean} [rateLimit] - Whether rate limiting is applied
 * @property {boolean} [cache] - Whether caching is enabled
 */

/**
 * @typedef {Object} Permission
 * @property {string} name - Permission name
 * @property {string} resource - Resource name
 * @property {string} action - Action name (create, read, update, delete)
 * @property {string} [description] - Permission description
 */

/**
 * @typedef {Object} Role
 * @property {string} name - Role name
 * @property {string} description - Role description
 * @property {Permission[]} permissions - Role permissions
 */